export type SceneNode = { id: string; x?: number; y?: number; z?: number; position?: Partial<QuantityPoint3> | number[] };
export type SizeCoordination = { kind: 'shared' | 'independent' | 'unspecified' | string; groupLabel?: string; group_label?: string };
export type SectionCoordination = { kind: 'shared' | 'independent' | 'unspecified' | string; groupLabel?: string; group_label?: string };
export type SceneMember = { id: string; role?: string; startNode?: string; endNode?: string; start_node?: string; end_node?: string; i?: string; j?: string; node_i?: string; node_j?: string; start?: string; end?: string; sectionId?: string; section_id?: string; allowedSectionFamilies?: string[]; allowed_section_families?: string[]; coordinationGroupId?: string; coordination_group_id?: string; coordinationGroupLabel?: string; coordination_group_label?: string; familyGroupLabel?: string; family_group_label?: string; sectionCoordination?: SectionCoordination; section_coordination?: SectionCoordination; sizeGroupLabel?: string; size_group_label?: string; sizeCoordination?: SizeCoordination; size_coordination?: SizeCoordination; schemeNote?: string; scheme_note?: string };
export type AgentSettings = { providerId?: string; provider_id?: string; modelId?: string; model_id?: string; model?: string; reasoningEffort?: string; reasoning_effort?: string };
export type AgentReasoningOption = { effort: string; description?: string };
export type AgentModelOption = { providerId?: string; provider_id?: string; modelId?: string; model_id?: string; slug?: string; displayName?: string; display_name?: string; defaultReasoningLevel?: string; default_reasoning_level?: string; supportedReasoningLevels?: AgentReasoningOption[]; supported_reasoning_levels?: AgentReasoningOption[]; available?: boolean; contextWindow?: number | null; context_window?: number | null; maxTokens?: number | null; max_tokens?: number | null };
export type AgentAuthenticationMethod = { type: 'oauth' | 'api_key' | 'external' | string; label: string; interactive: boolean; persistentAllowed?: boolean; persistent_allowed?: boolean; requirements?: string[] };
export type AgentProviderDescriptor = { id: string; name: string; authentication: AgentAuthenticationMethod[]; authState?: 'connected' | 'configured' | 'disconnected' | string; auth_state?: string; authType?: string | null; auth_type?: string | null; authSource?: string | null; auth_source?: string | null };
export type AgentCatalogueFreshness = { refreshedAt?: string | null; refreshed_at?: string | null; stale?: boolean; refreshError?: string | null; refresh_error?: string | null; source?: string };
export type AgentProviderStatus = { providers: AgentProviderDescriptor[]; models: AgentModelOption[]; selectedProviderId?: string; selected_provider_id?: string; selectedModelId?: string; selected_model_id?: string; selectedModel?: string; selected_model?: string; selectedReasoningEffort?: string; selected_reasoning_effort?: string; catalogue?: AgentCatalogueFreshness; secureCredentialStorageAvailable?: boolean; secure_credential_storage_available?: boolean; diagnostics?: unknown[] };
export type AiProviderCatalogue = { providers: AgentProviderDescriptor[]; models: AgentModelOption[]; catalogue: AgentCatalogueFreshness; secureCredentialStorageAvailable?: boolean; secure_credential_storage_available?: boolean };
export type AgentTarget = { kind: string; id: string };
export type UnitSystem = 'metric_structural' | string;
export type QuantityKind = 'length' | 'force' | 'line_load' | 'moment' | 'stress' | 'displacement' | 'area' | 'second_moment_area' | 'mass' | 'mass_per_length' | 'density';
export type Quantity = { value: number; quantityKind: QuantityKind; canonicalUnit: string; quantity_kind?: QuantityKind; canonical_unit?: string };
export type QuantityPoint3 = { x: number; y: number; z: number; quantityKind?: QuantityKind; canonicalUnit?: string; quantity_kind?: QuantityKind; canonical_unit?: string };
export type UnitFormat = { symbol: string; canonicalToDisplay: number; canonical_to_display?: number; precision: number };
export type UnitProfile = {
  id: string;
  label: string;
  system: UnitSystem;
  length: UnitFormat;
  force: UnitFormat;
  lineLoad: UnitFormat;
  line_load?: UnitFormat;
  moment: UnitFormat;
  stress: UnitFormat;
  displacement: UnitFormat;
  area?: UnitFormat;
  secondMomentArea?: UnitFormat;
  second_moment_area?: UnitFormat;
  mass?: UnitFormat;
  massPerLength?: UnitFormat;
  mass_per_length?: UnitFormat;
  density?: UnitFormat;
};
export type AgentQuestionOption = { id: string; label: string; value: string };
export type AgentQuestion = { id: string; prompt: string; options: AgentQuestionOption[]; allowsFreeText?: boolean; allows_free_text?: boolean };
export type AgentPlanItem = { id: string; title: string; summary: string; status: string; affectedTargets?: AgentTarget[]; affected_targets?: AgentTarget[]; proposedActions?: unknown[]; proposed_actions?: unknown[] };
export type AgentSuggestedReplyGroup = { title: string; prompt: string; replies: string[]; defaultReplies?: string[]; default_replies?: string[] };
export type AgentMessage = { author: string; text: string; createdAt?: string; created_at?: string; mode?: string; model?: string; providerId?: string; provider_id?: string; reasoningEffort?: string; reasoning_effort?: string; catalogueRefreshedAt?: string; catalogue_refreshed_at?: string; suggestedReplies?: string[]; suggested_replies?: string[]; suggestedReplyGroups?: AgentSuggestedReplyGroup[]; suggested_reply_groups?: AgentSuggestedReplyGroup[]; planSummary?: string; plan_summary?: string; proposedActions?: unknown[]; proposed_actions?: unknown[] };
export type AgentSession = { id: string; surface: string; title: string; status: string; messages: AgentMessage[]; planItems?: AgentPlanItem[]; plan_items?: AgentPlanItem[]; currentQuestion?: AgentQuestion | null; current_question?: AgentQuestion | null };
export type AgentState = { sessions: AgentSession[]; settingsBySurface?: Record<string, AgentSettings>; settings_by_surface?: Record<string, AgentSettings> };
export type BaseModelBrief = {
  version: number;
  sessionId?: string;
  session_id?: string;
  currentUnderstanding?: string;
  current_understanding?: string;
  confirmedIntent?: string[];
  confirmed_intent?: string[];
  openQuestions?: string[];
  open_questions?: string[];
  softAssumptions?: string[];
  soft_assumptions?: string[];
  schemaGuidance?: string[];
  schema_guidance?: string[];
  doNotDecideYet?: string[];
  do_not_decide_yet?: string[];
  visualIntent?: BaseModelBriefVisualIntent;
  visual_intent?: BaseModelBriefVisualIntent;
  readiness?: {
    readyForSchemas?: boolean;
    ready_for_schemas?: boolean;
    unresolvedTopics?: string[];
    unresolved_topics?: string[];
    manualOverrideAllowed?: boolean;
    manual_override_allowed?: boolean;
  };
  updatedAt?: string;
  updated_at?: string;
};
export type BaseModelBriefVisualIntent = {
  supportLocations?: BaseModelBriefSupportLocationIntent[];
  support_locations?: BaseModelBriefSupportLocationIntent[];
  loads?: BaseModelBriefLoadIntent[];
};
export type BaseModelBriefSupportLocationIntent = { id: string; targetNode?: string; target_node?: string; label?: string | null; status: 'location_only' | string };
export type BaseModelBriefLoadTarget = { kind: 'all_members' | 'member' | 'node' | string; memberId?: string | null; member_id?: string | null; nodeId?: string | null; node_id?: string | null };
export type BaseModelBriefLoadDirection = { kind: 'toward_node' | 'vector' | string; fromNode?: string | null; from_node?: string | null; toNode?: string | null; to_node?: string | null; x?: number | null; y?: number | null; z?: number | null };
export type BaseModelBriefLoadIntent = { id: string; kind: 'self_weight' | 'point' | 'uniform_line' | string; target?: BaseModelBriefLoadTarget; magnitude?: Quantity | number | null; magnitudeN?: number | null; magnitude_n?: number | null; magnitudeNPerM?: number | null; magnitude_n_per_m?: number | null; magnitudeKn?: number | null; magnitude_kn?: number | null; direction?: BaseModelBriefLoadDirection | null };
export type DesignOptionRevisionState = { revisionId?: string; revision_id?: string; optionId: string; option_id?: string; label: string; revisionOf?: string | null; revision_of?: string | null; included: boolean; analysisStatus: 'not_run' | 'current' | 'stale' | 'failed' | string; analysis_status?: string; latestAnalysisRunId?: string | null; latest_analysis_run_id?: string | null };
export type DesignOptionBatchState = { id: string; generatedAt: string; generated_at?: string; baseModelFingerprint: string; base_model_fingerprint?: string; status: 'active' | 'outdated' | 'superseded' | string; optionRevisions: DesignOptionRevisionState[]; option_revisions?: DesignOptionRevisionState[]; comparisonRuns: DesignOptionComparisonRunState[]; comparison_runs?: DesignOptionComparisonRunState[] };
export type DesignOptionComparisonEvidenceReferenceState = { optionRevisionId: string; option_revision_id?: string; analysisRunId: string; analysis_run_id?: string };
export type DesignOptionComparisonRunState = { runId: string; run_id?: string; createdAt: string; created_at?: string; optionIds: string[]; option_ids?: string[]; evidenceReferences?: DesignOptionComparisonEvidenceReferenceState[]; evidence_references?: DesignOptionComparisonEvidenceReferenceState[]; objective: string; recommendedOptionId?: string | null; recommended_option_id?: string | null; explanation: string; limitations: string[] };
export type DevelopmentPathState = { id: string; optionId: string; option_id?: string; optionRevisionId: string; option_revision_id?: string; status: string; createdAt: string; created_at?: string; updatedAt: string; updated_at?: string; sourceAnalysisRunId?: string | null; source_analysis_run_id?: string | null };
export type DesignOptionDecisionState = { activeBatchId?: string | null; active_batch_id?: string | null; batches: DesignOptionBatchState[]; activeDevelopmentPathId?: string | null; active_development_path_id?: string | null; developmentPaths: DevelopmentPathState[]; development_paths?: DevelopmentPathState[] };
export type WorkbenchState = { overview?: { projectDir?: string; project_dir?: string; [key: string]: any }; projectDir?: string; project_dir?: string; unitProfile?: UnitProfile; unit_profile?: UnitProfile; scene?: { nodes?: SceneNode[]; members?: SceneMember[]; supports?: RenderSupport[]; loads?: RenderLoad[]; releases?: RenderRelease[]; unitProfile?: UnitProfile; unit_profile?: UnitProfile }; agentState?: AgentState; agent_state?: AgentState; baseModelBrief?: BaseModelBrief; base_model_brief?: BaseModelBrief; analysisReadiness?: any; analysis_readiness?: any; planningDraft?: any; planning_draft?: any; designSchemes?: any[]; design_schemes?: any[]; latestDesignOptionAnalysis?: any; latest_design_option_analysis?: any; designOptionDecisions?: DesignOptionDecisionState; design_option_decisions?: DesignOptionDecisionState; [key: string]: any };
export type DesignOptionIntent = {
  id: string;
  label?: string;
  hypothesis?: string;
  explorationBand?: string;
  exploration_band?: string;
  lifecycleStatus?: 'active' | 'superseded' | 'rejected' | string | null;
  lifecycle_status?: 'active' | 'superseded' | 'rejected' | string | null;
  supersededBy?: string | null;
  superseded_by?: string | null;
  supersededReason?: string | null;
  superseded_reason?: string | null;
  revisionOf?: string | null;
  revision_of?: string | null;
  objectiveTags?: string[];
  objective_tags?: string[];
  standardisationStrategy?: string;
  standardisation_strategy?: string;
  connectionStrategy?: string;
  connection_strategy?: string;
  supportStrategy?: string;
  support_strategy?: string;
  sectionFamilyPolicy?: string;
  section_family_policy?: string;
  coordinationGroupPolicy?: string;
  coordination_group_policy?: string;
  coordinationOverrides?: {
    memberId?: string;
    member_id?: string;
    familyGroupLabel?: string | null;
    family_group_label?: string | null;
    designationGroupLabel?: string | null;
    designation_group_label?: string | null;
    note?: string | null;
  }[];
  coordination_overrides?: {
    memberId?: string;
    member_id?: string;
    familyGroupLabel?: string | null;
    family_group_label?: string | null;
    designationGroupLabel?: string | null;
    designation_group_label?: string | null;
    note?: string | null;
  }[];
  assumptions?: string[];
  provenance?: string[];
};
export type BackendDesignScheme = {
  id: string;
  label?: string;
  strategy?: string;
  summary?: string;
  differentiation?: string;
  lifecycleStatus?: 'active' | 'superseded' | 'rejected' | string | null;
  lifecycle_status?: 'active' | 'superseded' | 'rejected' | string | null;
  supersededBy?: string | null;
  superseded_by?: string | null;
  supersededReason?: string | null;
  superseded_reason?: string | null;
  revisionOf?: string | null;
  revision_of?: string | null;
  pros?: string[];
  cons?: string[];
  supportStrategy?: string;
  support_strategy?: string;
  standardisationStrategy?: string;
  standardisation_strategy?: string;
  connectionStrategy?: string;
  connection_strategy?: string;
  intent?: DesignOptionIntent | null;
  scene?: { nodes?: SceneNode[]; members?: SceneMember[]; supports?: RenderSupport[]; loads?: RenderLoad[]; releases?: RenderRelease[]; unitProfile?: UnitProfile; unit_profile?: UnitProfile };
  groupChoices?: BackendDesignSchemeGroupChoice[];
  group_choices?: BackendDesignSchemeGroupChoice[];
  approximateMassKg?: number;
  approximate_mass_kg?: number;
  analysisSummary?: { status?: string; maxUtilization?: number; max_utilization?: number; maxMomentKnm?: number | null; maxMomentKnM?: number | null; max_moment_knm?: number | null; maxShearKn?: number; max_shear_kn?: number; maxStressMpa?: number; max_stress_mpa?: number; maxDeflectionMm?: number; max_deflection_mm?: number; maxDriftMm?: number; max_drift_mm?: number; maxReactionKn?: number; max_reaction_kn?: number; governingMemberId?: string; governing_member_id?: string; deflectedShapeScale?: number; deflected_shape_scale?: number };
  analysis_summary?: { status?: string; maxUtilization?: number; max_utilization?: number; maxMomentKnm?: number | null; maxMomentKnM?: number | null; max_moment_knm?: number | null; maxShearKn?: number; max_shear_kn?: number; maxStressMpa?: number; max_stress_mpa?: number; maxDeflectionMm?: number; max_deflection_mm?: number; maxDriftMm?: number; max_drift_mm?: number; maxReactionKn?: number; max_reaction_kn?: number; governingMemberId?: string; governing_member_id?: string; deflectedShapeScale?: number; deflected_shape_scale?: number };
  resultPreview?: any;
  result_preview?: any;
  diagnostics?: unknown[];
};
export type BackendDesignSchemeSectionCandidate = { sectionId?: string; section_id?: string; family?: string; massKgPerM?: number; mass_kg_per_m?: number; approximateMassKg?: number; approximate_mass_kg?: number; relativeToSelectedKg?: number; relative_to_selected_kg?: number; analysisStatus?: string; analysis_status?: string; analysisRunId?: string; analysis_run_id?: string; passesPreliminaryCheck?: boolean; passes_preliminary_check?: boolean; maxUtilization?: number; max_utilization?: number; maxStressMpa?: number; max_stress_mpa?: number; maxMomentKnm?: number; max_moment_knm?: number; maxShearKn?: number; max_shear_kn?: number; maxDeflectionMm?: number; max_deflection_mm?: number; maxDriftMm?: number; max_drift_mm?: number; maxReactionKn?: number; max_reaction_kn?: number; governingMemberId?: string; governing_member_id?: string; diagnostic?: string | null };
export type BackendDesignSchemeGroupChoice = { coordinationGroupId?: string; coordination_group_id?: string; allowedSectionFamilies?: string[]; allowed_section_families?: string[]; candidateSectionIds?: string[]; candidate_section_ids?: string[]; candidateSections?: BackendDesignSchemeSectionCandidate[]; candidate_sections?: BackendDesignSchemeSectionCandidate[]; selectedSectionId?: string; selected_section_id?: string; approximateMassKg?: number; approximate_mass_kg?: number; notes?: string[]; checkStatus?: string; check_status?: string };
export type ChatMessage = { role: 'assistant'|'user'|'system'; content: string; chips?: string[]; proposals?: Array<{ id?: string; title?: string; summary?: string; actions?: unknown[]; affectedTargets?: unknown[] }>; readinessDelta?: string };
export type RenderNode = { id: string; x: number; y: number; z: number; source?: 'base' | 'scheme' };
export type RenderMember = { id: string; role: string; start: string; end: string; source?: 'base' | 'scheme'; allowedSectionFamilies?: string[]; coordinationGroupId?: string; coordinationGroupLabel?: string; familyGroupLabel?: string; sectionCoordination?: SectionCoordination; sizeGroupLabel?: string; sizeCoordination?: SizeCoordination; schemeNote?: string };
export type RenderSupport = { id: string; targetNode?: string; target_node?: string; ux?: boolean; uy?: boolean; uz?: boolean; rx?: boolean; ry?: boolean; rz?: boolean; supportGroupLabel?: string; support_group_label?: string };
export type RenderLoad = { id: string; kind?: string; magnitude?: number | Quantity; x?: number; y?: number; z?: number; directionX?: number; directionY?: number; directionZ?: number; direction_x?: number; direction_y?: number; direction_z?: number; targetLabel?: string; target_label?: string; targetMember?: string; target_member?: string; targetNode?: string; target_node?: string; memberId?: string; member_id?: string; semanticLabel?: string; semantic_label?: string };
export type RenderRelease = { id: string; memberId?: string; member_id?: string; end?: 'start' | 'end' | 'Start' | 'End' | string; ux?: boolean; uy?: boolean; uz?: boolean; rx?: boolean; ry?: boolean; rz?: boolean };
export type RenderScene = { nodes: RenderNode[]; members: RenderMember[]; supports: RenderSupport[]; loads: RenderLoad[]; releases?: RenderRelease[]; unitProfile?: UnitProfile };

export type BaseCleanupIssue = {
  id: string;
  severity: 'info' | 'warning';
  title: string;
  summary: string;
  proposedCorrection: string;
  confidence: 'low' | 'medium' | 'high';
  affectedTargets: AgentTarget[];
};
export type BaseCleanupProposal = { id: string; status: 'suggested' | 'accepted' | 'skipped'; issues: BaseCleanupIssue[] };
export type SchemeOperation = {
  id: string;
  kind: 'add_object' | 'modify_object' | 'suppress_base_object' | 'add_support' | 'add_load' | 'add_bracing';
  summary: string;
  affectedTargets: AgentTarget[];
};
export type SchemeTradeoff = { label: string; pros: string[]; cons: string[]; compromise: string };
export type EngineeringScheme = {
  id: string;
  name: string;
  status: 'concept' | 'needs_decision' | 'ready_to_solve' | 'solved' | 'superseded' | 'rejected';
  recommendation: string;
  summary: string;
  supersededBy?: string | null;
  supersededReason?: string | null;
  revisionOf?: string | null;
  assumptions: string[];
  operations: SchemeOperation[];
  tradeoffs: SchemeTradeoff[];
  intent?: DesignOptionIntent | null;
  approximateMassKg?: number | null;
  analysisSummary?: BackendDesignScheme['analysisSummary'] | null;
  groupChoices?: BackendDesignSchemeGroupChoice[];
  diagnostics?: unknown[];
  scene: RenderScene;
  comparison: { supportStrategy: string; bracingStrategy: string; loadStrategy: string; connectionImplication: string; readiness: string };
};
export type SchemeWorkspaceState = { baseScene: RenderScene; cleanup: BaseCleanupProposal; schemes: EngineeringScheme[] };
