[package]
name = "fraia-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
lopdf = { version = "0.44", default-features = false }
fraia-math = { path = "../fraia-math" }
fraia-geometry = { path = "../fraia-geometry" }
fraia-physics = { path = "../fraia-physics" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
